// Supplied VND company snapshot. Values and evidence labels are reproduced as provided.
export const companyOverviewIndicators = [
 ['Income statement & growth', [['Gross revenue','13.81T VND','Verified report'],['Revenue deductions','21.84B VND','Verified report'],['Net revenue','13.79T VND','Verified report'],['Revenue growth (YoY)','16.4%','Verified report'],['Cost of goods sold','9.51T VND','Verified report'],['Gross profit','4.28T VND','Verified report'],['Gross margin','31.0%','Derived'],['Operating profit','2.89T VND','Verified report'],['Operating margin','20.9%','Derived'],['EBITDA','3.32T VND','Verified report'],['EBITDA margin','24.1%','Verified report'],['Net income used in analysis','2.57T VND','Verified report'],['Parent-attributable profit','2.57T VND','Verified report'],['Total consolidated profit','2.57T VND','Verified report'],['Non-controlling interest profit','2.75B VND','Verified report'],['Selling expense','1T VND','Verified report'],['Administrative expense','1.28T VND','Verified report'],['SG&A','1.28T VND','Verified report'],['Depreciation','844.63B VND','Verified report'],['Net margin','18.6%','Verified report'],['Earnings growth (YoY)','13.4%','Market data']]],
 ['Capital & efficiency', [['Total assets','73.73T VND','Verified report'],['Total liabilities','32.74T VND','Verified report'],['Shareholders’ equity','41T VND','Verified report'],['Total liabilities & equity','73.73T VND','Verified report'],['Current assets','45.70T VND','Verified report'],['Current liabilities','29.37T VND','Verified report'],['Working capital','16.34T VND','Derived'],['Current ratio','1.56×','Derived'],['Receivables','13.50T VND','Verified report'],['Receivables / revenue','97.9%','Derived'],['Property, plant & equipment','10.66T VND','Verified report'],['Short-term debt','16.37T VND','Verified report'],['Long-term debt','2.08T VND','Verified report'],['Total debt','18.45T VND','Verified report'],['Debt / equity','0.45×','Derived'],['Return on equity','6.1%','Verified report'],['Return on assets','3.2%','Verified report'],['Debt / EBITDA','1.39×','Verified report'],['Net debt / EBITDA','-0.86×','Market data']]],
 ['Cash flow & reinvestment', [['Statement operating cash flow','-1.14T VND','Verified report'],['Cash flow margin','-8.3%','Verified report'],['Statement cash conversion','-44.6%','Derived'],['Operating cash flow (market)','7.31T VND','Market data'],['Free cash flow','-91.12B VND','Market data'],['Capital expenditure','Unavailable','Market data'],['Free cash flow margin','-0.7%','Derived'],['Free cash flow conversion','-3.5%','Derived']]],
 ['Valuation & market', [['Price','62,100 VND','Market data'],['Market capitalization','116.37T VND','Market data'],['P/E (trailing)','12.27×','Market data'],['Forward P/E','9.5×','Market data'],['Price / book','2.65×','Market data'],['EPS (trailing)','5,061 VND','Market data'],['Book value / share','23,394 VND','Market data'],['Beta (1Y)','0.42','Market data'],['Average volume (10D)','2,937,300','Market data'],['Shares outstanding','1,873,857,833','Market data']]],
 ['Shareholder returns', [['Dividend / share','1,818 VND','Market data'],['Dividend yield','2.9%','Market data'],['Payout ratio','35.9%','Market data'],['Ex-dividend date','28 May 2026','Market data'],['Market state','CLOSED','Market data']]],
 ['Evidence & coverage', [['Research score','81 / 100','Derived'],['Report quality','100 / 100','Verified report'],['Scanned line coverage','100.0%','Derived'],['Available report lines','26','Derived'],['Tracked report lines','26','Derived'],['Core indicator coverage','100.0%','Derived'],['Available core indicators','7','Derived'],['Indexed reports','4','Verified report']]],
].map(([name,rows])=>({name,rows:rows.map(([label,value,evidence])=>({label,value,evidence}))}));
