import React,{useState} from 'react';
import BrandLogo from './BrandLogo';
import Dialog from './Dialog';
import {articles} from './marketData';
import './landing.scss';
const services=[['01','Research with perspective','Compare companies, follow the evidence, and explore the story behind the numbers.','Company comparisons · Peer research'],['02','A portfolio in focus','Bring holdings, sector exposure, watchlists, and sample price alerts into one clear view.','Allocation · Risk · Watchlists'],['03','Plan your next move','Explore hypothetical events and define the risk, entry, and target of a trade draft.','Scenarios · Position sizing']];
export default function LandingPage({onLogin,onRegister}){
 const [menu,setMenu]=useState(false),[article,setArticle]=useState(null);
 const nav=[['Wealth','wealth'],['Solutions','solutions'],['Research','research'],['About','about']];
 return <div className="slate-site"><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><div className="site-container header-inner"><a className="site-brand" href="#" aria-label="PASION home"><BrandLogo/></a><button className="site-menu-button" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="site-navigation" onClick={()=>setMenu(v=>!v)}>{menu?'Close ✕':'Menu ☰'}</button><nav id="site-navigation" className={menu?'open':''} aria-label="Website navigation">{nav.map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<button className="site-button outline" onClick={onLogin}>Client Login</button><button className="site-button" onClick={onRegister}>Get Started <span>↗</span></button></nav></div></header>
 <main id="main-content"><section className="site-hero"><div className="site-container hero-grid"><div className="hero-copy"><span className="site-eyebrow">PERSPECTIVE DRIVES PERFORMANCE</span><h1>Trusted Guidance<br/>for a <em>Changing</em>{' '}<br/>World</h1><p>Clear insights and thoughtful research tools to help you plan your next move.</p><a className="site-button" href="#solutions">Explore Our Solutions <span>→</span></a><div className="hero-signature"><span/><p>A wider perspective.<br/><strong>A clearer way forward.</strong></p></div></div><div className="hero-visual"><img className="architecture-image" src="/news/macro.jpg" alt="Modern glass architecture viewed against a clear sky"/><div className="architecture-fade"/><div className="hero-image-caption">STRUCTURE. CLARITY. PERSPECTIVE.</div><div className="floating-portfolio"><div className="portfolio-preview-heading"><span>GLOBAL PORTFOLIO</span><span className="preview-mark">↗</span></div><strong className="preview-value">$245,800<span>.00</span></strong><div className="preview-performance"><span>↗ +6.8%</span><small>Sample performance</small></div><svg className="world-preview" viewBox="0 0 300 120" aria-hidden="true"><g fill="#dce9f3"><path d="m15 28 27-13 31 5 14 14-11 13-16-1-9 19-14-8-9-18-13-3zM62 67l18 4 10 17-9 28-12-14-2-21zM112 21l22-9 15 12-8 16-12 4-9-13zM134 48l21 3 12 24-14 27-16-15-10-28zM148 18l40-9 49 11 32 19-12 24-31-6-13 18-16-5-16-26-29 1-16-11zM239 85l21-7 18 10-5 17-25-4z"/></g><g fill="#6f98b9"><circle cx="58" cy="34" r="4"/><circle cx="139" cy="29" r="4"/><circle cx="213" cy="44" r="4"/></g><path d="M58 34Q95 0 139 29T213 44" fill="none" stroke="#98b9d4" strokeDasharray="3 4"/></svg><div className="allocation-track"><i/><i/><i/><i/></div><div className="preview-allocation">{[['Equities','35%'],['Fixed income','30%'],['Alternatives','20%'],['Cash','15%']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="illustrative-label">Illustrative portfolio · Not account data</p></div></div></div></section>
 <section id="wealth" className="site-capabilities"><div className="site-container capabilities-row"><div><span className="site-eyebrow">A CLEARER VIEW</span><h2>Built around your perspective.</h2></div><div><strong>One workspace</strong><span>Research, portfolios & planning</span></div><div><strong>Transparent data</strong><span>Clearly marked sample insights</span></div><div><strong>Your pace</strong><span>Focused views & saved preferences</span></div></div></section>
 <section id="solutions" className="site-section site-container"><div className="site-section-heading"><div><span className="site-eyebrow">THOUGHTFUL TOOLS</span><h2>Clarity for every<br/>step of your journey.</h2></div><p>From your first question to a fuller investment picture, make room for informed exploration.</p></div><div className="service-cards">{services.map(([number,title,body,caption])=><article key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{body}</p><small>{caption}</small><button className="site-text-link" onClick={onRegister}>Explore the workspace <span>→</span></button></article>)}</div></section>
 <section id="about" className="site-about"><div className="site-container about-grid"><div className="about-photo"><img src="/news/economy.jpg" alt="A calm modern workspace with clean architectural lines"/><div><span className="site-eyebrow">THE PASION PERSPECTIVE</span><p>See the whole picture.</p></div></div><div className="about-copy"><span className="site-eyebrow">STRUCTURE MEETS PERSPECTIVE</span><h2>A considered approach<br/>to a complex world.</h2><p>PASION brings company research, market context, and portfolio tools together. Explore how the pieces connect, keep your questions in focus, and build a research routine that works for you.</p><p className="about-disclosure">This is a demonstration workspace. Prices, news, and research metrics are illustrative. Live market and advisory services are not connected.</p><button className="site-text-link" onClick={onLogin}>Discover your workspace <span>→</span></button></div></div></section>
 <section className="site-section site-container"><div className="site-section-heading"><div><span className="site-eyebrow">A SIMPLE START</span><h2>From curiosity to clarity.</h2></div></div><div className="journey-steps">{[['01','Make it yours','Create an account and choose the views that fit your research style.'],['02','Connect the picture','Explore companies, compare their metrics, and build a sample portfolio.'],['03','Keep perspective','Save watchlists, set sample alerts, and revisit your trade drafts.']].map(([n,title,text])=><div key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
 <section id="research" className="site-insights"><div className="site-container"><div className="site-section-heading"><div><span className="site-eyebrow">IDEAS WORTH EXPLORING</span><h2>A wider perspective.</h2></div><span className="site-sample-tag">Illustrative insights</span></div><div className="site-article-grid">{articles.slice(0,3).map((a,i)=><button key={a.id} onClick={()=>setArticle(a)}><img src={'/news/'+['macro','economy','energy'][i]+'.jpg'} alt="" loading="lazy"/><div><span className="site-eyebrow">{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p><span className="site-text-link">Read perspective →</span></div></button>)}</div></div></section>
 <section className="site-cta"><div className="site-container"><span className="site-eyebrow">YOUR NEXT CHAPTER</span><h2>A clearer picture starts here.</h2><p>Make space for thoughtful research and a more focused portfolio view.</p><button className="site-button" onClick={onRegister}>Get Started <span>→</span></button></div></section></main>
 <footer className="site-footer"><div className="site-container footer-grid"><div><a href="#" aria-label="PASION home"><BrandLogo/></a><p>Perspective drives performance.<br/>See the whole picture.</p></div><div><span>EXPLORE</span>{nav.map(([label,id])=><a key={id} href={'#'+id}>{label}</a>)}</div><div><span>YOUR WORKSPACE</span><button onClick={onLogin}>Client Login</button><button onClick={onRegister}>Create an account</button><p>Account assistance is provided by<br/>your PASION administrator.</p></div></div><div className="site-container footer-bottom"><span>© {new Intl.DateTimeFormat('en',{timeZone:'Asia/Baku',year:'numeric'}).format(new Date())} PASION</span><p>Demonstration research tools. Illustrative data. No live trading or advisory service.</p></div></footer>
 {article&&<Dialog title={article.title} onClose={()=>setArticle(null)}><span className="site-sample-tag">Illustrative insight · {article.category}</span><p className="tool-body">{article.summary}</p><p className="tool-body">{article.body}</p></Dialog>}</div>
}
