import React,{useState,useEffect} from 'react';
import {companies,articles,money,percent} from './marketData';
import PriceChart from './PriceChart';
import Dialog from './Dialog';
import {usePreferences} from './Preferences';
import './workspace.scss';
import {Newsroom} from './CompanyNews';
export {Newsroom};

export const layouts={Home:['Focus Pulse','Heatmap Command Center','Morning Market Brief','Analyst Canvas'],Research:['Evidence Split','Peer Rail','Research Matrix','Sector Radar','Story and Benchmark'],News:['Morning Edition','Three-Desk Newsroom','Reading Focus','Signal Timeline','Topic Library'],Portfolio:['Portfolio Cockpit','Holdings Board','Risk First','Change Timeline','Sector Groups']};
export function LayoutPicker({page,value,onChange}){const {t:translate}=usePreferences();return layouts[page]&&<div className="layout-picker"><span>{translate("YOUR VIEW")}</span><div role="group" aria-label={translate("Workspace layout")}>{layouts[page].map((label,i)=><button key={label} aria-pressed={value===i} onClick={()=>onChange(i)}>{translate(label)}</button>)}</div></div>}
export function FocusView({variant,onChoose,onArticle,watched}){
 const {t:translate}=usePreferences();
 if(!variant||variant>=layouts.Home.length)return null;
 return <section className={'home-card focus-view focus-'+variant}><header><span className="eyebrow">{translate(layouts.Home[variant])}</span><h2>{translate(['','The market, at a glance.','Your morning in three signals.','Build a clearer investment picture.'][variant])}</h2></header>{variant===1?<div className="command-heatmap">{companies.map(c=><button key={c.ticker} style={{'--heat':c.change<0?'#fce2e6':'#d5f4e8'}} onClick={()=>onChoose(c)}><strong>{c.ticker}</strong><span>{percent(c.change)}</span><small>{translate(c.sector)}</small></button>)}</div>:variant===2?<div className="morning-signals">{articles.slice(0,3).map((a,i)=><button onClick={()=>onArticle(a)} key={a.id}><b>0{i+1}</b><h3>{a.title}</h3><p>{a.summary}</p><span>{translate("Read briefing →")}</span></button>)}</div>:variant===3?<div className="analyst-canvas">{watched.slice(0,3).map(c=><button key={c.ticker} onClick={()=>onChoose(c)}><h3>{c.ticker}</h3><PriceChart company={c} compact/><p>{translate(c.detail)}</p></button>)}{!watched.length&&<p>{translate("Add companies to your watchlist to start your canvas.")}</p>}</div>:null}</section>
}
const metrics=['Revenue growth','Operating margin','ROE','Net debt / EBITDA'];
function values(c){return [12+c.index*2,17-c.index%8,24-c.index%12,.3+c.index*.08]}
export function ResearchAssessment({company,variant,onChoose}){
 const {t:translate}=usePreferences();
 const [step,setStep]=useState('Accounting Quality'),[tab,setTab]=useState('Metrics');
 const peers=[company,...companies.filter(c=>c.sector===company.sector&&c.ticker!==company.ticker).slice(0,3)];
 return <section className={'research-assessment assessment-'+variant}><div className="assessment-heading"><div><strong>{company.ticker}</strong><div><h2>{company.name}</h2><span>{translate("{sector} · US equities",{sector:translate(company.sector)})}</span></div></div><div className="assessment-steps">{['Accounting Quality','Core Value'].map((s,i)=><button key={s} aria-pressed={step===s} onClick={()=>setStep(s)}><b>{i+1}</b>{translate(s)}</button>)}</div><span className="small-tag">{translate("SAMPLE DATA")}</span></div>
 <div className="home-card verdict-grid"><div><span className="eyebrow">{translate(step==='Accounting Quality'?'ACCOUNTING QUALITY VERDICT':'CORE VALUE SCENARIO')}</span><div className="verdict"><span>♢</span><div><strong>{translate(step==='Accounting Quality'?'Good':'Balanced')}</strong><p>{translate(step==='Accounting Quality'?'Essential quality checks pass in this sample assessment.':'Valuation is broadly aligned with the sample peer group.')}</p></div></div></div><div className="coverage"><h3>{translate(step==='Accounting Quality'?'Evidence coverage':'Scenario confidence')}</h3><strong>{step==='Accounting Quality'?'86%':'72%'}</strong><progress value={step==='Accounting Quality'?86:72} max="100"/><small>{translate(step==='Accounting Quality'?'28 of 33 checks with usable sample data':'Based on illustrative assumptions')}</small></div><div className="warning-drivers"><h3>{translate(step==='Accounting Quality'?'Top warning drivers':'Valuation sensitivities')}</h3>{(step==='Accounting Quality'?['Rising receivables','Higher goodwill','Lower cash conversion']:['Revenue assumptions','Discount rate','Terminal growth']).map((label,i)=><div key={label}><span>{i===2?'!':'△'}</span><div><strong>{translate(label)}</strong><small>{translate(['Monitor trends against revenue growth.','Compare with historical levels.','Review supporting evidence.'][i])}</small></div><b className={i===2?'high':''}>{translate(i===2?'High':'Moderate')}</b></div>)}</div><div className="verdict-action"><button className="dashboard-button" onClick={()=>setStep(step==='Accounting Quality'?'Core Value':'Accounting Quality')}>{translate(step==='Accounting Quality'?'Continue to Core Value':'Back to Accounting Quality')} →</button><p>{translate("Connect evidence with your valuation assumptions.")}</p></div></div>
 <section className="home-card peer-section"><div className="card-heading"><div><h2>{translate("{sector} peers · automatically matched",{sector:translate(company.sector)})}</h2><p>{translate("Matched by sector in this sample universe.")}</p></div><div className="company-tabs">{['Metrics','Evidence'].map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{translate(t)}</button>)}</div></div>{variant===3?<div className="sector-radar">{[...new Set(companies.map(c=>c.sector))].map(s=><button key={s} onClick={()=>onChoose(companies.find(c=>c.sector===s))}><span>{translate(s)}</span><strong>{companies.filter(c=>c.sector===s).length}</strong><small>{translate("companies to explore →")}</small></button>)}</div>:<div className="peer-grid">{peers.map(c=><article className={'peer-card '+(c.ticker===company.ticker?'reference':'')} key={c.ticker}><button className="peer-company" onClick={()=>onChoose(c)}><span style={{color:c.color}}>{c.ticker}</span><div><strong>{c.name}</strong><small>{translate(c.sector)}</small></div></button>{tab==='Metrics'?metrics.map((label,i)=><div className="peer-metric" key={label}><span>{translate(label)}</span><b>{i===3?values(c)[i].toFixed(1)+'x':values(c)[i]+'%'}</b><i><em style={{width:Math.min(100,values(c)[i]*(i===3?70:3))+'%'}}/></i></div>):<div className="peer-evidence"><p>{translate(c.detail)}</p><ul><li>{translate("Financial statements: sample")}</li><li>{translate("Sector classification: matched")}</li><li>{translate("Confidence: illustrative")}</li></ul></div>}<div className="peer-note">{translate(c.ticker===company.ticker?'★ Reference company':'Sector peer')}</div></article>)}</div>}{variant===4&&<div className="benchmark-story"><h3>{translate("The story behind the numbers")}</h3><p>{translate(company.detail)} {translate("Compare growth, profitability, and leverage together. These metrics demonstrate the analysis workflow and do not represent verified financial statements.")}</p></div>}<div className="takeaway-bar"><strong>{translate("Key takeaways vs. peers")}</strong><span>{translate("✓ Compare growth quality")}</span><span>{translate("✓ Check profitability")}</span><span>{translate("◉ Review leverage")}</span></div></section>
 </section>
}
const portfolioUniverse=[
 {ticker:'VCB',name:'Vietcombank',sector:'Banking',shares:700,cost:82000,price:89000,day:1.1,color:'#3164e8'},
 {ticker:'MWG',name:'MWG Investment',sector:'Consumer',shares:350,cost:56000,price:58500,day:.8,color:'#28a999'},
 {ticker:'HPG',name:'Hoa Phat Group',sector:'Materials',shares:1200,cost:27000,price:29200,day:1.5,color:'#56b3df'},
 {ticker:'FPT',name:'FPT Corporation',sector:'Technology',shares:1000,cost:55000,price:62100,day:1.97,color:'#735ee7'},
 {ticker:'CMG',name:'CMG Corporation',sector:'Technology',shares:400,cost:42000,price:43800,day:.7,color:'#10a879'},
];
const initialHoldings=portfolioUniverse.map(({ticker,shares,cost})=>({ticker,shares,cost}));
const formatVnd=value=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Math.round(value||0))+' VND';
const formatQuantity=value=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(value||0);
function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback}catch{return fallback}}
export function PortfolioMonitor({variant,storageKey,watchlist,onChoose,initialTab='Holdings'}){
 const [holdings,setHoldings]=useState(()=>load(storageKey+'-portfolio-vnd',initialHoldings).filter(h=>portfolioUniverse.some(c=>c.ticker===h.ticker)&&Number.isFinite(h.shares)&&h.shares>0&&Number.isFinite(h.cost)&&h.cost>=0));
 const [alerts,setAlerts]=useState(()=>load(storageKey+'-portfolio-alerts-vnd',[]).filter(a=>portfolioUniverse.some(c=>c.ticker===a.ticker)&&Number.isFinite(a.target)&&a.target>0));
 const [tab,setTab]=useState(initialTab),[adding,setAdding]=useState(false),[alertFor,setAlertFor]=useState(null);
 const [symbol,setSymbol]=useState('FPT'),[shares,setShares]=useState('10'),[cost,setCost]=useState(''),[target,setTarget]=useState('');
 const [query,setQuery]=useState(''),[period,setPeriod]=useState('YTD'),[alertFilter,setAlertFilter]=useState('All alerts'),[saveError,setSaveError]=useState('');
 useEffect(()=>setTab(initialTab),[initialTab]);
 useEffect(()=>{try{localStorage.setItem(storageKey+'-portfolio-vnd',JSON.stringify(holdings));localStorage.setItem(storageKey+'-portfolio-alerts-vnd',JSON.stringify(alerts));setSaveError('')}catch{setSaveError('Portfolio changes could not be saved on this browser.')}},[holdings,alerts,storageKey]);

 const rows=holdings.map(h=>({...h,company:portfolioUniverse.find(c=>c.ticker===h.ticker)})).filter(h=>h.company);
 const marketValue=rows.reduce((n,h)=>n+h.shares*h.company.price,0);
 const costBasis=rows.reduce((n,h)=>n+h.shares*h.cost,0);
 const profit=marketValue-costBasis,cash=marketValue*.192/.808,total=marketValue+cash;
 const dayPnl=rows.reduce((n,h)=>n+h.shares*h.company.price*h.company.day/100,0);
 const exposure=[...new Set(rows.map(h=>h.company.sector))].map(sector=>({sector,rows:rows.filter(h=>h.company.sector===sector),value:rows.filter(h=>h.company.sector===sector).reduce((n,h)=>n+h.shares*h.company.price,0)})).sort((a,b)=>b.value-a.value);
 const allocation=[...rows.map(h=>({label:h.ticker,name:h.company.name,value:h.shares*h.company.price,color:h.company.color})),{label:'Cash',name:'Cash reserve',value:cash,color:'#17ad83'}];
 const largest=allocation.filter(item=>item.label!=='Cash').sort((a,b)=>b.value-a.value)[0];
 const concentration=total?(largest?.value||0)/total*100:0,cashWeight=total?cash/total*100:0;
 const active=alerts.filter(a=>!a.acknowledged&&(portfolioUniverse.find(c=>c.ticker===a.ticker)?.price||0)>=a.target);
 const visiblePriceAlerts=alerts.filter(a=>{const price=portfolioUniverse.find(c=>c.ticker===a.ticker)?.price||0,reached=price>=a.target;return !a.acknowledged&&((alertFilter==='All alerts'&&reached)||(alertFilter==='Triggered'&&reached)||(alertFilter==='Watching'&&!reached))});
 const filteredRows=rows.filter(h=>(h.company.ticker+' '+h.company.name+' '+h.company.sector).toLowerCase().includes(query.toLowerCase()));
 const filteredAlerts=alerts.filter(a=>{const c=portfolioUniverse.find(item=>item.ticker===a.ticker),triggered=c?.price>=a.target;return alertFilter==='All alerts'||alertFilter==='HIGH'||alertFilter==='MEDIUM'||alertFilter==='LOW'||(alertFilter==='Triggered'&&triggered&&!a.acknowledged)||(alertFilter==='Watching'&&(!triggered||a.acknowledged))});
 const holdingSlices=marketValue?allocation.map(item=>item.color+' '+item.value/total*100+'%').join(','):'#e8eef5 0% 100%';
 const curveOffset={'1M':3,'3M':6,YTD:0,'1Y':-4,ALL:-8};
 const chartValues=Array.from({length:36},(_,i)=>50+Math.sin(i*.39)*9+Math.sin(i*.13)*17+i*.48+(curveOffset[period]||0));
 const benchmarkValues=Array.from({length:36},(_,i)=>48+Math.sin(i*.37+1)*8+Math.sin(i*.12)*13+i*.34);
 const linePath=values=>values.map((v,i)=>(i?'L':'M')+' '+(i/(values.length-1))*1000+' '+(190-v*1.5)).join(' ');
 function saveHolding(e){e.preventDefault();const count=Number(shares),company=portfolioUniverse.find(c=>c.ticker===symbol),basis=cost===''?company.price:Number(cost);if(!company||!Number.isFinite(count)||count<=0||!Number.isFinite(basis)||basis<=0)return;setHoldings(list=>{const old=list.find(h=>h.ticker===symbol);return old?list.map(h=>h.ticker===symbol?{ticker:symbol,shares:h.shares+count,cost:(h.shares*h.cost+count*basis)/(h.shares+count)}:h):[...list,{ticker:symbol,shares:count,cost:basis}]});setAdding(false)}
 function saveAlert(e){e.preventDefault();const value=Number(target);if(!Number.isFinite(value)||value<=0)return;setAlerts(list=>[...list,{id:Date.now(),ticker:alertFor,target:value,acknowledged:false}]);setAlertFor(null)}
 function openRiskLog(){document.getElementById('portfolio-alerts')?.scrollIntoView({behavior:'smooth',block:'start'})}

 const portfolioAlerts=[
  {level:'HIGH',kind:'HIGH CONCENTRATION',title:(largest?.label||'Portfolio')+' represents '+concentration.toFixed(1)+'% of total portfolio value.',detail:'A position is above the 25% sample limit. Review concentration before adding exposure.',date:'Today · 10:30 AM'},
  {level:'MEDIUM',kind:'LOW CASH RESERVE',title:'Available cash ('+cashWeight.toFixed(1)+'%) is below the 20% sample buffer.',detail:'Consider reviewing portfolio liquidity before the next planned investment.',date:'Today · 9:15 AM'},
  {level:'MEDIUM',kind:'RESEARCH REVISION',title:'VCB earnings preview updated with a revised target.',detail:'Illustrative research signal: compare new assumptions with your original thesis.',date:'Oct 05 · 9:00 AM'},
  {level:'LOW',kind:'STALE DATA',title:'CMG valuation snapshot is due for review.',detail:'Sample valuation inputs can age. Confirm reporting periods before relying on them.',date:'Oct 02 · 11:20 AM'},
 ];
 const visiblePortfolioAlerts=portfolioAlerts.filter(a=>alertFilter==='All alerts'||a.level===alertFilter);
 const groupedRows=exposure.map(group=>({...group,rows:group.rows.filter(h=>filteredRows.includes(h))})).filter(group=>group.rows.length);
 const watchRows=companies.filter(company=>watchlist.includes(company.ticker));
 const table=<section className="portfolio-holdings-card">
  <div className="portfolio-section-heading">
   <div><div className="portfolio-tabs" role="tablist" aria-label="Portfolio views">{['Holdings','Watchlist','Alerts'].map(label=><button key={label} role="tab" aria-selected={tab===label} className={tab===label?'selected':''} onClick={()=>setTab(label)}>{label}<span>{label==='Holdings'?rows.length:label==='Watchlist'?watchRows.length:alerts.length}</span></button>)}</div><p>{tab==='Holdings'?'Your positions, grouped by industry.':tab==='Watchlist'?'Saved companies from your research workspace.':'Price targets saved for these sample holdings.'}</p></div>
   <div className="portfolio-holdings-tools">{tab!=='Alerts'&&<label className="portfolio-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg><input aria-label="Search holdings" placeholder="Search holdings…" value={query} onChange={e=>setQuery(e.target.value)}/></label>}{tab==='Holdings'&&<button className="portfolio-primary-button" onClick={()=>{setSymbol('FPT');setCost('');setShares('10');setAdding(true)}}><span aria-hidden="true">＋</span> Add holding</button>}</div>
  </div>
  {tab==='Holdings'?<div className="portfolio-industry-list">{groupedRows.map(group=><section className="portfolio-industry" key={group.sector}>
   <header><div className="portfolio-industry-title"><span className="portfolio-industry-mark" style={{'--industry-color':group.rows[0].company.color}} aria-hidden="true"/><div><strong>{group.sector}</strong><small>{group.rows.length} {group.rows.length===1?'holding':'holdings'} <i/> {marketValue?((group.value/marketValue)*100).toFixed(1):'0.0'}% of invested holdings</small></div></div><div className="portfolio-industry-total"><small>INDUSTRY VALUE</small><strong>{formatVnd(group.value)}</strong></div></header>
   <div className="portfolio-table-scroll"><table className="portfolio-table-vnd"><thead><tr><th>COMPANY</th><th>QUANTITY</th><th>AVG COST</th><th>CURRENT PRICE</th><th>MARKET VALUE</th><th>P&amp;L</th><th>WEIGHT</th><th aria-label="Actions"/></tr></thead><tbody>{group.rows.map(h=>{const value=h.shares*h.company.price,pnl=value-h.shares*h.cost,returnPct=h.cost?pnl/(h.shares*h.cost)*100:0,weight=total?value/total*100:0;return <tr key={h.ticker}>
    <td><div className="portfolio-company-cell"><span style={{'--company-color':h.company.color}}>{h.ticker.slice(0,2)}</span><div><strong>{h.company.name}</strong><small>{h.ticker}</small></div></div></td><td>{formatQuantity(h.shares)}</td><td>{formatVnd(h.cost)}</td><td className="portfolio-current-price">{formatVnd(h.company.price)}</td><td className="portfolio-market-value">{formatVnd(value)}</td>
    <td><strong className={pnl>=0?'portfolio-positive':'portfolio-negative'}>{pnl>=0?'+':''}{formatVnd(pnl)}</strong><small className={pnl>=0?'portfolio-positive':'portfolio-negative'}>{returnPct>=0?'+':''}{returnPct.toFixed(2)}%</small></td>
    <td><div className="portfolio-weight"><span>{weight.toFixed(1)}%</span><i><b style={{width:Math.min(weight*2,100)+'%'}}/></i></div></td><td><button className="portfolio-row-alert" aria-label={'Set '+h.ticker+' price alert'} onClick={()=>{setTarget(String(h.company.price));setAlertFor(h.ticker)}}>Set alert</button><button className="portfolio-row-remove" aria-label={'Remove '+h.ticker} onClick={()=>setHoldings(list=>list.filter(item=>item.ticker!==h.ticker))}>Remove</button></td>
   </tr>})}</tbody></table></div>
  </section>)}{!groupedRows.length&&<div className="portfolio-empty">{query?'No holdings match your search.':'Add a holding to start building your portfolio.'}</div>}</div>
  :tab==='Watchlist'?<div className="portfolio-watchlist-table"><p className="portfolio-watchlist-note">Watchlist quotes use the workspace’s separate USD sample market.</p>{watchRows.map(company=><div key={company.ticker}><button onClick={()=>onChoose(company)}><strong>{company.ticker}</strong><span>{company.name}</span></button><span>{money(company.price)}</span><b className={company.change>=0?'portfolio-positive':'portfolio-negative'}>{percent(company.change)}</b><button onClick={()=>onChoose(company)}>View research</button></div>)}{!watchRows.length&&<div className="portfolio-empty">No saved companies yet. Save a company from its research page.</div>}</div>
  :<div className="portfolio-saved-alerts">{filteredAlerts.map(alert=>{const company=portfolioUniverse.find(item=>item.ticker===alert.ticker),triggered=company.price>=alert.target;return <article key={alert.id}><div><strong>{alert.ticker} · Price target</strong><small>{company.name} · Target {formatVnd(alert.target)} · {triggered?'Target reached in sample data':'Watching sample price'}</small></div><button onClick={()=>setAlerts(list=>list.map(item=>item.id===alert.id?{...item,acknowledged:!item.acknowledged}:item))}>{alert.acknowledged?'Reopen':'Acknowledge'}</button><button className="portfolio-delete-alert" onClick={()=>setAlerts(list=>list.filter(item=>item.id!==alert.id))}>Delete</button></article>})}{!filteredAlerts.length&&<div className="portfolio-empty">No price alerts match this filter.</div>}</div>}
 </section>;

 const allocationCard=<section className="portfolio-card portfolio-allocation"><header className="portfolio-card-heading"><div><h2>Portfolio allocation</h2><p>Market value by position, including cash reserve</p></div></header><div className="portfolio-allocation-content"><div className="portfolio-donut" style={{background:'conic-gradient('+holdingSlices+')'}} role="img" aria-label="Portfolio allocation by holding"><div><small>PORTFOLIO VALUE</small><strong>{formatVnd(total)}</strong><span>{rows.length} positions + cash</span></div></div><div className="portfolio-allocation-legend">{allocation.map(item=><div key={item.label}><i style={{background:item.color}}/><span>{item.label==='FPT'?'FPT (Tech)':item.label==='VCB'?'VCB (Bank)':item.label==='HPG'?'HPG (Steel)':item.name}</span><strong>{total?(item.value/total*100).toFixed(1):'0.0'}%</strong></div>)}</div></div><p className="portfolio-chart-disclaimer">Positions and reserve use illustrative VND sample data.</p></section>;

 const performance=<section className="portfolio-card portfolio-performance"><header className="portfolio-card-heading"><div><h2>Portfolio performance</h2><p>Illustrative portfolio trend compared with the VN-Index benchmark</p></div><div className="portfolio-periods" aria-label="Performance period">{['1M','3M','YTD','1Y','ALL'].map(item=><button key={item} aria-pressed={period===item} onClick={()=>setPeriod(item)}>{item}</button>)}</div></header><div className="portfolio-chart-legend"><span><i className="portfolio-legend-portfolio"/>Portfolio</span><span><i className="portfolio-legend-benchmark"/>VN-Index</span><b>{profit>=0?'+':''}{costBasis?(profit/costBasis*100).toFixed(2):'0.00'}% total return</b></div><div className="portfolio-line-chart"><div className="portfolio-y-labels"><span>+20%</span><span>+10%</span><span>0%</span><span>−10%</span></div><svg viewBox="0 0 1000 220" preserveAspectRatio="none" role="img" aria-label={period+' illustrative portfolio performance chart'}><defs><linearGradient id="portfolio-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2864e8" stopOpacity=".22"/><stop offset="100%" stopColor="#2864e8" stopOpacity="0"/></linearGradient></defs><path className="portfolio-chart-gridline" d="M0 40H1000M0 90H1000M0 140H1000M0 190H1000"/><path className="portfolio-benchmark-line" d={linePath(benchmarkValues)}/><path className="portfolio-area" d={linePath(chartValues)+' L1000 220 L0 220 Z'}/><path className="portfolio-main-line" d={linePath(chartValues)}/></svg></div><div className="portfolio-x-labels"><span>{period==='1M'?'Sep 08':period==='3M'?'Jul':period==='YTD'?'Jan':'Oct 2025'}</span><span>{period==='1M'?'Sep 15':period==='3M'?'Aug':period==='YTD'?'Mar':'Jan'}</span><span>{period==='1M'?'Sep 22':period==='3M'?'Sep':period==='YTD'?'May':'Apr'}</span><span>{period==='1M'?'Sep 29':period==='3M'?'Oct':period==='YTD'?'Jul':'Jul'}</span><span>{period==='1M'?'Oct 07':period==='3M'?'Nov':period==='YTD'?'Oct':'Oct 2026'}</span></div><p className="portfolio-chart-disclaimer">Illustrative history for interface demonstration; not a verified account statement.</p></section>;

 const riskPanel=<section className="portfolio-status-strip"><span className="portfolio-status-mark" aria-hidden="true">!</span><strong>PORTFOLIO STATUS: ATTENTION REQUIRED</strong><span>Largest position {concentration.toFixed(1)}% · cash reserve {cashWeight.toFixed(1)}% · {active.length} triggered price alerts</span><button onClick={openRiskLog}>View risk log</button></section>;
 const portfolioAttention=<section className="portfolio-attention" id="portfolio-alerts"><header><div><h2>Needs attention</h2><span>{visiblePortfolioAlerts.length+visiblePriceAlerts.length} actionable items</span></div><select aria-label="Filter portfolio alerts" value={alertFilter} onChange={e=>setAlertFilter(e.target.value)}>{['All alerts','HIGH','MEDIUM','LOW','Triggered','Watching'].map(item=><option key={item}>{item}</option>)}</select></header><div className="portfolio-attention-grid">{visiblePortfolioAlerts.map((alert,index)=><article className={'portfolio-attention-card attention-'+alert.level.toLowerCase()} key={alert.kind}><div className="portfolio-attention-label"><span/><strong>{alert.kind}</strong><b>{alert.level}</b></div><h3>{alert.title}</h3><p>{alert.detail}</p><footer><span>{alert.date}</span><button onClick={index===0?openRiskLog:()=>setTab(index===2?'Watchlist':'Holdings')}>View details <span aria-hidden="true">→</span></button></footer></article>)}
 {visiblePriceAlerts.map(alert=><article className="portfolio-attention-card attention-medium" key={'price-'+alert.id}><div className="portfolio-attention-label"><span/><strong>PRICE TARGET</strong><b>{portfolioUniverse.find(company=>company.ticker===alert.ticker)?.price>=alert.target?'TRIGGERED':'WATCHING'}</b></div><h3>{alert.ticker} {portfolioUniverse.find(company=>company.ticker===alert.ticker)?.price>=alert.target?'reached':'is approaching'} your {formatVnd(alert.target)} target.</h3><p>Illustrative market data. Review the position and your original plan.</p><footer><span>Just now</span><button onClick={()=>setTab('Alerts')}>View alert <span aria-hidden="true">→</span></button></footer></article>)}</div></section>;
 const exposureCard=<section className="portfolio-card portfolio-exposure"><header><h2>Exposure breakdown</h2><p>See where your portfolio is concentrated</p></header><div className="portfolio-exposure-columns"><div><h3>SECTOR EXPOSURE</h3>{exposure.map(group=><div className="portfolio-exposure-row" key={group.sector}><div><span>{group.sector}</span><strong>{total?(group.value/total*100).toFixed(1):'0.0'}%</strong></div><i><b style={{width:(total?group.value/total*100:0)+'%',background:group.rows[0].company.color}}/></i></div>)}<div className="portfolio-exposure-row"><div><span>Cash reserve</span><strong>{cashWeight.toFixed(1)}%</strong></div><i><b style={{width:cashWeight+'%',background:'#17ad83'}}/></i></div></div><div><h3>CURRENCY EXPOSURE</h3><div className="portfolio-exposure-row"><div><span>VND · Vietnamese Dong</span><strong>{marketValue&&total?(marketValue/total*100).toFixed(1):'0.0'}%</strong></div><i><b style={{width:(marketValue&&total?marketValue/total*100:0)+'%',background:'#3164e8'}}/></i></div><div className="portfolio-exposure-row"><div><span>Cash reserve · VND</span><strong>{cashWeight.toFixed(1)}%</strong></div><i><b style={{width:cashWeight+'%',background:'#99a8bb'}}/></i></div></div><div><h3>COMMODITY &amp; FACTOR EXPOSURE</h3>{[['Technology cycle','HIGH'],['Domestic consumption','MEDIUM'],['Foreign capital flow','MEDIUM'],['Commodity prices','LOW']].map(([label,level])=><div className="portfolio-factor" key={label}><span>{label}</span><b className={'factor-'+level.toLowerCase()}>{level}</b></div>)}</div></div></section>;

 return <section className={'portfolio-monitor-v2 portfolio-layout-'+variant}>
  {saveError&&<p className="portfolio-save-error" role="alert">{saveError}</p>}
  <section className="portfolio-overview-stats" aria-label="Portfolio summary">
   <article><span>PORTFOLIO VALUE</span><strong>{formatVnd(total)}</strong><small className={profit>=0?'portfolio-positive':'portfolio-negative'}>Overall return {costBasis?((profit/costBasis*100>=0?'+':'')+(profit/costBasis*100).toFixed(2)):'0.00'}%</small></article>
   <article><span>INVESTED</span><strong>{formatVnd(marketValue)}</strong><small>{total?(marketValue/total*100).toFixed(1):'0.0'}% allocation</small></article>
   <article><span>AVAILABLE CASH</span><strong>{formatVnd(cash)}</strong><small>{cashWeight.toFixed(1)}% allocation</small></article>
   <article><span>TODAY’S P&amp;L</span><strong className={dayPnl>=0?'portfolio-positive':'portfolio-negative'}>{dayPnl>=0?'+':''}{formatVnd(dayPnl)}</strong><small className={dayPnl>=0?'portfolio-positive':'portfolio-negative'}>↗ {(marketValue?dayPnl/marketValue*100:0).toFixed(2)}% today · sample</small></article>
   <article><span>TOTAL P&amp;L</span><strong className={profit>=0?'portfolio-positive':'portfolio-negative'}>{profit>=0?'+':''}{formatVnd(profit)}</strong><small className={profit>=0?'portfolio-positive':'portfolio-negative'}>↗ {(costBasis?profit/costBasis*100:0).toFixed(2)}% unrealized</small></article>
  </section>
  <div className="portfolio-main-column">{table}{riskPanel}<div className="portfolio-chart-grid">{allocationCard}{performance}</div>{exposureCard}{portfolioAttention}</div>
  {adding&&<Dialog title="Add a holding" onClose={()=>setAdding(false)}><form className="portfolio-form" onSubmit={saveHolding}><label htmlFor="portfolio-vn-company">Company<select id="portfolio-vn-company" value={symbol} onChange={e=>setSymbol(e.target.value)}>{portfolioUniverse.map(company=><option key={company.ticker} value={company.ticker}>{company.ticker} — {company.name}</option>)}</select></label><label>Quantity<input type="number" min="0.0001" step="any" required value={shares} onChange={e=>setShares(e.target.value)}/></label><label>Average cost (VND)<input type="number" min="1" step="any" placeholder="Use sample current price" value={cost} onChange={e=>setCost(e.target.value)}/></label><p>Added holdings use illustrative VND prices and are saved in this browser.</p><button className="portfolio-primary-button">Save holding</button></form></Dialog>}
  {alertFor&&<Dialog title={'Set '+alertFor+' price alert'} onClose={()=>setAlertFor(null)}><form className="portfolio-form" onSubmit={saveAlert}><p>We’ll show the alert when the illustrative price reaches your target.</p><label>Target price (VND)<input type="number" min="1" step="any" value={target} onChange={e=>setTarget(e.target.value)} required/></label><button className="portfolio-primary-button">Save alert</button></form></Dialog>}
 </section>
}export {default as PlansDialog} from './PlansDialog';
